#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"




int main(void)
{
	RCC_voidInitSysClock();
	/* Enable RCC for GPIOA */
	RCC_voidEnableClock(RCC_APB2,RCC_APB2_GPIOAEN);
	/* Enable RCC for GPIOB */
	RCC_voidEnableClock(RCC_APB2,RCC_APB2_GPIOBEN);
	/* Enable RCC for GPIOC */
	RCC_voidEnableClock(RCC_APB2,RCC_APB2_GPIOCEN);

	/* Pin A Output Push Pull  10 MHz */
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN0 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN1 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN2 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN3 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN4 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN5 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN6 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN7 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN8 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN9 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN10 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN11 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN12 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN13 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN14 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTA , GPIO_u8_PIN15 , GPIO_OUTPUT_10MHZ_PUSH_PULL);


	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN0 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN1 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN2 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN3 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN4 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN5 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN6 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN7 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN8 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN9 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN10 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN11 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN12 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN13 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN14 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTB , GPIO_u8_PIN15 , GPIO_OUTPUT_10MHZ_PUSH_PULL);


	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN0 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN1 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN2 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN3 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN4 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN5 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN6 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN7 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN8 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN9 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN10 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN11 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN12 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN13 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN14 , GPIO_OUTPUT_10MHZ_PUSH_PULL);
	MGPIO_voidSetPinDirection(GPIO_u8_PORTC , GPIO_u8_PIN15 , GPIO_OUTPUT_10MHZ_PUSH_PULL);


	//u16 w =500 ;

	while(1)
	{
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN0 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN1 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN2 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN3 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN4 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN5 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN6 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN7 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN8 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN9 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN10 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN11 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN12 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN13 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN14 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTA, GPIO_u8_PIN15 , GPIO_u8_HIGH);

		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN0 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN1 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN2 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN3 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN4 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN5 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN6 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN7 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN8 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN9 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN10 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN11 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN12 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN13 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN14 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTB, GPIO_u8_PIN15 , GPIO_u8_HIGH);

		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN0 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN1 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN2 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN3 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN4 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN5 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN6 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN7 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN8 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN9 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN10 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN11 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN12 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN13 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN14 , GPIO_u8_HIGH);
		MGPIO_voidSetPinValue(GPIO_u8_PORTC, GPIO_u8_PIN15 , GPIO_u8_HIGH);

	}

	return 0;
}
